$('span.message')
$('div.box')
$('button')
$('img[alt= "hello"]')
$('#myDiv input[type="text"]')
$('input[name^=txt]')
$('p:not(.box)')
$('div.box, div.error')
$('div.box.error')
$('#myDiv span.info')